contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #tautyping channel"
    url: https://nfcore.slack.com/channels/tautyping
    about: Discussion about the nf-core/tautyping pipeline
